server:
  port: 8086

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/usersystem"
    username: "fawry"
    password: "fawry"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem